#!/bin/sh
# mus - lemonbar script to get music

sym=""

playing=$(mpc status | sed -n 2p | cut -d " " -f 1 | tr -d "[]")

if [ "$playing" = "playing" ] ; then
    sym2=""
elif [ "$playing" = "paused" ] ; then
    sym2=""
fi

out=$(mpc current -f "[%artist% ; %title%]|[%file%]")

if [ "$out" = "" ]; then
    out="stopped"
fi

echo "%{R} ${sym2} %{R}  $out"
