#!/bin/sh
# blk - print colors 0,1,3,5,7 (for my custom color layout)

printf="/bin/printf"

esc0="\e[30m"
esc1="\e[31m"
esc2="\e[33m"
esc3="\e[35m"
esc4="\e[37m"

clear
tput civis

$printf " ${esc0}█████████${esc1}█████████${esc2}█████████${esc3}█████████${esc4}█████████ \n"
$printf " ${esc0}█████████${esc1}█████████${esc2}█████████${esc3}█████████${esc4}█████████ \n"
$printf " ${esc0}█████████${esc1}█████████${esc2}█████████${esc3}█████████${esc4}█████████ \n"
$printf " ${esc0}█████████${esc1}█████████${esc2}█████████${esc3}█████████${esc4}█████████"
$printf "\e[0m"

read _

$printf "  #$(gtc 0)  #$(gtc 1)  #$(gtc 3)  #$(gtc 5)  #$(gtc 7) \n"

tput cnorm
