#!/bin/sh

printf="/bin/printf"

esc0="\e[30m"
esc1="\e[31m"
esc2="\e[33m"
esc3="\e[35m"
esc4="\e[37m"

clear
tput civis

$printf " ${esc0}█████████${esc1}█████████${esc2}█████████${esc3}█████████${esc4}█████████ \n"
$printf " ${esc0}█████████${esc1}█████████${esc2}█████████${esc3}█████████${esc4}█████████ \n"
$printf " ${esc0}█████████${esc1}█████████${esc2}█████████${esc3}█████████${esc4}█████████ \n"
$printf " ${esc0}█████████${esc1}█████████${esc2}█████████${esc3}█████████${esc4}█████████"
$printf "\e[0m"

read _

$printf "  #$(getcol 0)  #$(getcol 1)  #$(getcol 3)  #$(getcol 5)  #$(getcol 7) \n"

tput cnorm
