#!/bin/sh

while read -r line; do
    case $line in
        W*) window="%{c}"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ]; do
                case $1 in
                    O*) window="${window}%{F#$(getcol 4)}%{F-}"
                        ;;
                    F*) window="${window}%{F#$(getcol 4)}%{F-}"
                        ;;
                    U*) window="${window}%{F#$(getcol 4)}{F-}"
                        ;;
                    o*) window="${window}%{F#$(getcol 7)}%{F-}"
                        ;;
                    f*) window="${window}%{F#$(getcol 15)}%{F-}"
                        ;;
                    u*) window="${window}%{F#$(getcol 7)}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    echo "$window"
done
