#!/bin/sh
# inf - get system infos

_hi="$(tput setaf 1)"
_fg="$(tput setaf fg)"

_user="$(whoami)"
_host="$(hostname)"
_distro="arch"
_kernel="$(uname -sr)"
_pkg="$(pacman -Q | wc -l)"
_shell="${SHELL}"
_wm="$(grep -v ^# ~/.xinitrc | tail -n 1 | cut -d' ' -f2)"
_up_day="$()"

_art_1="${_hi}        ;;;;        ${_fg}"
_art_2="${_hi}       ; ;;;;       ${_fg}"
_art_3="${_hi}      ;;;;;;;;      ${_fg}"
_art_4="${_hi}     ;;;;;;;;;;     ${_fg}"
_art_5="${_hi}    ;;;;;;;;;;;;    ${_fg}"
_art_6="${_hi}   ;;;;;;  ;;;; ;   ${_fg}"
_art_7="${_hi}  ;;;;;;    ;;;;;;  ${_fg}"
_art_8="${_hi} ;;;;;        ;;;;; ${_fg}"

# hacky: adjust ${_user} to align username width
_info_1="   ${_user} ${_hi};${_fg} ${_host}"
_info_2="  distro ${_hi};${_fg} ${_distro}"
_info_3="packages ${_hi};${_fg} ${_pkg}"
_info_4="   shell ${_hi};${_fg} ${_shell}"
_info_5="      wm ${_hi};${_fg} ${_wm}"
_info_6=""
_info_7=""

printf "$_art_1"
printf "$_info_1"
printf "\n"

printf "$_art_2"
printf "$_info_2"
printf "\n"

printf "$_art_3"
printf "$_info_3"
printf "\n"

printf "$_art_4"
printf "$_info_4"
printf "\n"

printf "$_art_5"
printf "$_info_5"
printf "\n"

printf "$_art_6"
printf "$_info_6"
printf "\n"

printf "$_art_7"
printf "$_info_7"
printf "\n"

printf "$_art_8"
printf "$_info_8"
printf "\n"

printf "\n"
