#!/bin/sh

sym=""

playing=$(mpc status | sed -n 2p | cut -d " " -f 1)

if [ "$playing" = "\[playing\]" ] ; then
    sym2=""
elif [ "$playing" = "\[paused\]" ] ; then
    sym2=""
fi

out=$(mpc current -f "[%artist% ; %title%]|[%file%]")

if [ "$out" = "" ]; then
    out="stopped"
fi

if [ "$1" = "-s" ]; then
    echo "$out"
else
    echo "%{R} ${sym} %{R}  $out"
fi
