#!/bin/sh
# pkg - pacman wrapper

pkgmgr='pacaur --color=auto --noedit'

usage() 
{
    cat << EOF
usage: $(basename $0) [ir package] [q query] [suc]
    i ; install package
    r ; remove package
    q ; list installed packages
    u ; system update
    s ; search
    c ; clean unneeded packages
EOF
    exit 1
}

case "$1" in 
    i|install)
        shift
        $pkgmgr -S $@
        ;;
    r|remove)
        shift
        $pkgmgr -Rns $@
        ;;
    q|query)
        shift
        $pkgmgr -Q $@
        ;;
    u|upgrade)
        $pkgmgr -Syu
        ;;
    s|search)
        shift
        $pkgmgr -Ss $@
        ;;
    c|clean)
        $pkgmgr -Rns $($pkgmgr -Qdtq) 2>/dev/null || \
            printf "no packages to clean\n"
        ;;
    *)
        $pkgmgr $@
        ;;
esac
