#!/bin/sh
# pop - lemonbar popup

# pkill lemonbar

font="-sxthe-terra-*-*-*-*-*-*-*-*-*-*-*-*"
glyphs="-*-siji-*-*-*-*-*-*-*-*-*-*-*-*"

fg="`gtc 1`"
altfg="`gtc 1`"
bg="`gtc bg`"
name="popupbar"

# time to stay up
sleep=5

# Create the popup and make it live for 3 seconds
(echo "    $@    "; sleep $sleep) | \
    lemonbar -d -f "$font" -f "$glyphs" -F \#$fg -B \#$bg -n "$name" \
    -g 250x25+15+40 | sh
