#!/bin/sh
# pop - lemonbar popup

# pkill lemonbar

font="-sxthe-yuki-*-*-*-*-*-*-*-*-*-*-*-*"
glyphs="-*-siji-*-*-*-*-*-*-*-*-*-*-*-*"

fg=$(gtc 1)
altfg=$(gtc 3)
bg="ff$(gtc bg)"
name="popupbar"

# time to stay up
sleep=3

# Create the popup and make it live for 3 seconds
(echo "%{l}$@"; sleep $sleep) | \
    lemonbar -d -f "$font" -f "$glyphs" -F \#$fg -B \#$bg -n "$name" \
    -g ${length:-250}x${height:-25}+${xpos:-50}+${ypos:-30} | sh
