#!/bin/sh

fg=$(getcol 1)
altfg=$(getcol 3)
borderfg=$(getcol 1)
bg=$(getcol bg)

font="-sythe-tangerine-*-*-*-*-*-*-*-*-*-*-*-*"
glyphs="siji:pixelsize=10"

height=30
duration=3
barw=${barw:-200}
barh=${barh:-30}
barx=${barx:-1116}
bary=${bary:-20}

args="-f $glyphs -f $font -F #$fg -B #$bg -u 3 -g ${barw}x${barh}+${barx}+${bary}"

# Create the popup and make it live for 3 seconds
(echo "%{c}$@"; sleep ${duration}) | \
    lemonbar ${args} | sh &
