#!/bin/sh
# run - dmenu with options

dmenu_run -fn -sxthe-yuki-*-*-*-*-*-*-*-*-*-*-*-* \
    -nb \#$(gtc bg) \
    -nf \#$(gtc 5) \
    -sb \#$(gtc bg) \
    -sf \#$(gtc 1) \
    -p ";" \
    -h 25 \
    -x 375 \
    -y 20 \
    -w 616
