#!/bin/sh

# get rid of any other bars
pkill lemonbar

# configs
. ~/.barconf

wrk()
{
    # NUMB=$(xprop -root -notype _NET_CURRENT_DESKTOP | cut -d= -f2);
    NUMB="$(cat /tmp/workspaces/curr)";
    case "$NUMB" in
        "0")
            WORKSPACE="$altfgf%{F-}${w1}$altfgf${w2}${w3}${w4}${w5}${w6}%{F-}";;
        "1")
            WORKSPACE="$altfgf${w1}%{F-}${w2}$altfgf${w3}${w4}${w5}${w6}%{F-}";;
        "2")
            WORKSPACE="$altfgf${w1}${w2}%{F-}${w3}$altfgf${w4}${w5}${w6}%{F-}";;
        "3")
            WORKSPACE="$altfgf${w1}${w2}${w3}%{F-}${w4}$altfgf${w5}${w6}%{F-}";;
        "4")
            WORKSPACE="$altfgf${w1}${w2}${w3}${w4}%{F-}${w5}$altfgf${w6}%{F-}";;
        "5")
            WORKSPACE="$altfgf${w1}${w2}${w3}${w4}${w5}%{F-}${w6}$altfgf%{F-}";;
        *)
            WORKSPACE="$altfgf${w1}${w2}${w3}${w4}${w5}${w6}$fg";;
    esac
    echo "$WORKSPACE"
}

while true; do
    buf="%{c}$(~/bin/bar/clk)    $(~/bin/bar/dat)" 
    echo "$buf"
    sleep 1
done | lemonbar \
    -f $glyphs \
    -f $font \
    -F \#$fg \
    -B \#$bg \
    -u 3 \
    -d \
    -g ${barlength}x${barheight}+50+20 | sh &
