#!/bin/sh

font="-sxthe-yuki-*-*-*-*-*-*-*-*-*-*-*-*"
glyphs="-*-siji-*-*-*-*-*-*-*-*-*-*-*-*"

fg=$(getcol 1)
altfg=$(getcol 3)
bg=$(getcol bg)

while true; do
    buf=""
    buf="${buf}$(mus)"
    buf="${buf}%{c}$(wrk)"
    echo "        $buf        "
    sleep 1
done | lemonbar -d -f "$font" -f "$glyphs" -F \#$fg -B \#$bg -g x25
