#!/bin/sh
# tdo - manage todo files

file="$HOME/usr/doc/todo"

[ -e "$file" ] || touch $file

usage() 
{
    printf  "usage: $(basename $0) [le] [ar item]\n"
    exit 1
}

prn()
{
    printf "  t             d       \n"
    printf "ttttt  ooo   dddd   ooo \n"
    printf "  t   o   o d   d  o   o\n"
    printf "  t   o   o d   d  o   o\n"
    printf "   t   ooo   dddd   ooo \n"
    nl $file
}

case "$1" in 
    l|list)
        prn ;;
    a|add)
        shift
        echo "$@" >> $file
        prn
        ;;
    r|remove)
        [ -n "$2" ] \
            && sed -i -e $2'd' $file \
            || usage
        prn
        ;;
    e|edit)
        ${EDITOR:-vim} $file ;;
    "")
        prn ;;
    *)
        usage ;;
esac
