#!/bin/sh
# tdo - manage todo files

file="$HOME/usr/doc/todo"

[ -e "$file" ] || touch $file

usage() 
{
    printf  "usage: $(basename $0) [le] [ar item]\n"
    exit 1
}

prt()
{
    printf "    t             d       \n"
    printf "  ttttt  ooo   dddd   ooo \n"
    printf "    t   o   o d   d  o   o\n"
    printf "    t   o   o d   d  o   o\n"
    printf "     t   ooo   dddd   ooo \n\n"
    nl $file
}

case "$1" in 
    l|list)
        prt ;;
    a|add)
        shift
        echo "$@" >> $file
        prt
        ;;
    r|remove)
        [ -n "$2" ] \
            && sed -i -e $2'd' $file \
            || usage
        prt
        ;;
    e|edit)
        $EDITOR $file ;;
    "")
        prt ;;
    *)
        usage ;;
esac
