#!/bin/bash

CUR=${2:-$(pfw)}
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)

BW=$(wattr b $CUR)
W=$(wattr w $CUR)
H=$(wattr h $CUR)

gap=10
X=$gap
Y=$gap

case $1 in
    tm) X=$((SW/2 - W/2 - BW)) ;;
    tr) X=$((SW - W - BW * 2 - $gap)) ;;
    ml) Y=$((SH/2 - H/2 - BW)) ;;
    mm) X=$((SW/2 - W/2 - BW))
        Y=$((SH/2 - H/2 - BW)) ;;
    mr) X=$((SW - W - BW * 2 - $gap))
        Y=$((SH/2 - H/2 - BW)) ;;
    bl) Y=$((SH - H - BW * 2 - $gap)) ;;
    bm) X=$((SW/2 - W/2 - BW))
        Y=$((SH - H - BW * 2 - $gap)) ;;
    br) X=$((SW - W - BW * 2 - $gap))
        Y=$((SH - H - BW * 2 - $gap)) ;;
esac

wtp $X $Y $W $H $CUR
