#!/bin/sh

while IFS=: read ev wid; do
    case $ev in
        # creation
        16) wattr o $wid || (focusw $wid && cornerw mm $wid) ;;

        # mapping req
        19) wattr o $wid || focusw $wid ;;

        # window deletion
        18) wattr $(pfw) || focusw prev 2> /dev/null ;;
    esac
done
