#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# window focus wrapper that sets borders and can focus next/previous window

borderwidth=${borderwidth:-3}
focusedcol=${focuscol:-0x$(getcol 1)}
unfocusedcol=${unfocusedcol:-0x$(getcol 7)}

# get current window id
CUR=$(pfw)

usage()
{
    echo "usage: $(basename $0) <next|prev|wid>"
    exit 1
}

setborder()
{
    ROOT=$(lsw -r)

    wattr $2 || return

    test "$(wattr xywh $2)" = "$(wattr xywh $ROOT)" && return

    case $1 in
        focused)
            chwb -s $borderwidth -c $focusedcol $2 ;;
        unfocused)
            chwb -s $borderwidth -c $unfocusedcol $2 ;;
    esac
}

case $1 in
    next) wattr o $wid || wid=$(lsw | grep -v $CUR | sed '1 p;d') ;;
    prev) wattr o $wid || wid=$(lsw | grep -v $CUR | sed '$ p;d') ;;
    0x*) wattr $1 && wid=$1 ;;
    *) usage ;;
esac

test -z "$wid" && echo "$(basename $0): can't find a window to focus" >&2 && exit 1

setborder unfocused $CUR
setborder focused $wid
chwso -r $wid
wtf $wid
