#!/bin/sh
#
# winopen - perform actions based on different windows
# (c) ix && wildefyr 2016
#

usage() {
  echo "usage: $(basename $0) <wid>"
  exit 1
}

if [ -z $1 ]; then
  usage
fi

wid=$1
windowc=$(winclass -c $wid)
windowm=$(winclass -m $wid)

setborder active $wid

if ! wattr o $wid; then
  if [ "$windowc" = "bar" ]; then
    sleep 1
  else
    wmv -a $(wmp) "$wid"
  fi
fi

