#!/bin/sh

. ~/.config/barconf

sym=""

playing=$(mpc status | sed -n 2p | cut -d " " -f 1)

if [ $playing = "\[playing\]" ] ; then
    sym2=""
elif [ $playing = "\[paused\]" ] ; then
    sym2=""
fi

out=$(mpc current -f "[%artist% ; %title%]|[%file%]")

if [ "$1" = "-s" ]; then
    printf "$out"
else
    printf "$sym $out"
fi
