#!/bin/sh

playing=$(mpc status | sed -n 2p | awk '{print $1}')

if [ $playing = "[playing]" ] ; then
    sym=""
elif [ $playing = "[paused]" ] ; then
    sym=""
fi

out=$(mpc current -f "[[%artist%|%album%]; %title%]|%file%")

if [ "$1" = "-s" ]; then
    printf "$out"
else
    printf "$sym $out"
fi
